export const REGION_TIMEZONE = {
  'South Korea': 'Asia/Seoul',
  'United States': 'America/New_York',
  'Japan': 'Asia/Tokyo',
  'China': 'Asia/Shanghai',
  'United Kingdom': 'Europe/London',
  'Germany': 'Europe/Berlin',
  'France': 'Europe/Paris',
  'Canada': 'America/Toronto',
  'Australia': 'Australia/Sydney',
  'Singapore': 'Asia/Singapore',
  'Hong Kong': 'Asia/Hong_Kong',
  'Taiwan': 'Asia/Taipei',
  'Thailand': 'Asia/Bangkok',
  'Vietnam': 'Asia/Ho_Chi_Minh',
  'Indonesia': 'Asia/Jakarta',
  'Philippines': 'Asia/Manila',
  'Malaysia': 'Asia/Kuala_Lumpur',
  'India': 'Asia/Kolkata',
  'Brazil': 'America/Sao_Paulo',
  'Mexico': 'America/Mexico_City',
  'Netherlands': 'Europe/Amsterdam',
  'Sweden': 'Europe/Stockholm',
  'Norway': 'Europe/Oslo',
  'Denmark': 'Europe/Copenhagen',
  'Finland': 'Europe/Helsinki',
  'Spain': 'Europe/Madrid',
  'Italy': 'Europe/Rome',
  'Poland': 'Europe/Warsaw',
  'Russia': 'Europe/Moscow',
};

export const REGION_NAMES = Object.keys(REGION_TIMEZONE);
